name: Test environment deployment

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: pnpm build:release
      # - name: Deploy homepage
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.RELEASE_HOST }}
      #     username: ${{ secrets.RELEASE_USERNAME }}
      #     passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
      #     key: ${{ secrets.RELEASE_KEY }}
      #     port: ${{ secrets.RELEASE_PORT }}
      #     source: 'packages/homepage/dist/*'
      #     target: '/app/homepage/release'
      #     strip_components: 3
      # - name: Deploy dashboard
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.RELEASE_HOST }}
      #     username: ${{ secrets.RELEASE_USERNAME }}
      #     passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
      #     key: ${{ secrets.RELEASE_KEY }}
      #     port: ${{ secrets.RELEASE_PORT }}
      #     source: 'packages/web/dist/*'
      #     target: '/app/web/release'
      #     strip_components: 3
      - name: Notification
        uses: erguotou520/instant-access-action@0.0.4
        if: ${{ success() }}
        with:
          channel: '3fa27c0affa54c069e428af95f0f98fa'
          head: '{{branchName}} deploy succeed!'
          body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
      - name: Notification
        uses: erguotou520/instant-access-action@0.0.4
        if: ${{ failure() }}
        with:
          channel: '3fa27c0affa54c069e428af95f0f98fa'
          head: '{{branchName}} deploy failed!'
          body: '{{author}} commit "{{commitMessage}}" on {{repositoryName}}#{{branchName}} branch at {{commitTime}}'
